# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c62af1353ddc4655b59f6ea71a60114ced39c6868be0142406ed388f10f4accd9e8e911767ebb74ccb708598f8558f465ae86ec4674b7684313661e4c2387496

test:
  secret_key_base: 6731b161bab77edbef9635fe72327007ca7719783bca1887df342af36aa435cde81566a0048e42cee335cd3b6b5036e98cbb04f746cead6773279291d4150238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
